os.loadAPI("/apis/graphix")
graphix.bgColor(colors.blue)
graphix.center(1,"CodeBox by Aperture")
graphix.center(3,"Coded by datcoder1208 and with help")
graphix.center(4,"from our trusty partners:")
graphix.center(6,"CubeSpace")
graphix.center(7,"Spectrum")
print()
graphix.center(9,"Thanks for using CodeBox!")
sleep(5)
shell.run("startgui")
